services:
  api:
    container_name: api
    build: 
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./api:/app
      - api_node_modules:/app/node_modules
    env_file:
      - ./api/.env
    environment:
      - NODE_ENV=development
    depends_on:
      - db
  web:
    container_name: web
    build: 
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./web:/app
      - web_node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - db
  db:
    image: mariadb:latest
    container_name: db
    restart: always
    env_file:
      - ./api/.env
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  api_node_modules:
  web_node_modules:
  db_data: